language: ruby
rvm:
- 2.2.3
before_script:
- chmod +x ./script/cibuild
script: "./script/cibuild"
branches:
  only:
  - master
  - gh-pages
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  secure: HXk4aDr8kJLQF18ZBuARGNHN6AY4gCxTsqHSBgfek5HUfdlGhizAOthcXRHWl8Y8cfRa3JaMx9gZS4YLZb4CuKD9F064twR5gnwnFKkeT6dFRfrYGy9erCaWWH6vGdw9hNYH0TjJgq5/Yy3MpfXlGlUALZEy/AJad/+70BSrcVga/eKaboOdQVfjPZIAl7TPjnGXDxRR5I6gGp+GoW27FhI5JhVXlfLXlJWW38+PBUqI+o9ykhEZ+Eep9ysx1LrIpvJ7IRt6XvuWrDHdG4ETALTLVVjhprC0Ohe1hiBH2pZ2L0spRaE3DqCPM2gjxy9Ib/sd5I0ccIEqRu19s/wDJe5uLvzYx37gXm7iidStbBjBlVufgucc98YCvqVPaHO9u0cpz3r/AJLJbWRB5fCdMza1WpYUqpf7SJ5cXNKb2/WLm6ESg+g7W7XHOwbAv/cdKNGRpoUSDDN1erZ+b3q7Aqw7Gsi3OxH4fL/mgd8EOxKqWOhVM/7aNKZkVaQuZlRCDoicIlakOm6xGYFoL3t0jef2HWx/Yx9lzDNXWRQQAp4583C7ARGPaRAugUJbiPSN8jl4qIHhBsPA0HJQmIM9MOp5rJ5eBZ/RLUi//N64ZwBubfug1jwM0zSGVtCFrCFQ/o9uLgRHqdKFS1Ev7ybJ+NCd0W29I/vNkZl79Wy7Muc=
  secure: Uf5IBWf6wKH14h4nPnvhKw3Drg7CQ4eLextQaK5fJj+SwhTc9CGESsTEZx05QYGvxgwlXVeba0aclU7Pe+lZV/Nj10OwAcONYbRneKp8xCp2fxlcgGnX/T8KwioOwK+PjHMiDaSvFAxzUIcizELwSIdafEg00vT0s/vLqvwcYJurGD5lwsREsM6jHFgdVgeVdvdvmelPSKharouUFxXlgDPZIyV3YJYa/Rk19ATmzbRcYPkHrPj3XgeEv8s+cZ/RiMnf12nQFS/0FJiIJGpO/lKzKylTY4U5XySU/4nrFBD1oGmQFNjJ1FdvcPp7627O/VZImG6criW8STw2ptOgWhumb6/iS8O7meF4WOUN1X4GUSJL8AT7TWkHJNj/uTY+XNN9bxTtDGCo6IgFffAFVt5MmuEXhFbnwbS+m7/xsD190iVTI79EYltIqxGyBKgvZ10nHNvlTvJploGuzZ3yO5kKO4WWB/vu85VzE0o5McuSRYyNtX9kvlcomjDpq5r98BuNjQRQNQyQutJhV09xi/dE4Vofs8aTVJd2KeiO1rQ3UmEsXKProG02WLWvYed8eMLlH8aMlSvVuQVRBDSz5vljVzVwcLTwt1JCuZs6IwSQ5jqqWb55SyYBiC35F9gmijgrMf5XXI+9rh6VMx8ttSu9q2/WxbdWS0vLq+s7668=
sudo: false
after_success: find _site -type f -exec curl -u $FTP_USER:$FTP_PASSWORD --ftp-create-dirs -T {} ftp://ftp.manchestercurious.com/manchestercurious.com/public_html/showcase/{} \;
