language: ruby
rvm:
- 2.2.3
before_script:
- chmod +x ./script/cibuild
script: "./script/cibuild"
branches:
  only:
  - master
  - gh-pages
env:
  secure:
  - DrYM0HIbrcxto3+1jibB6IUuSamKMz2dmneq8/Tj0EJ+GfprwaN23zWSD3PTD9cekeLvMIKZgFDTAF0ML9xDhlhsiGl3LmTSxXdQJWXCeuTzuY5XI7tzlZQQqG5LGTskqpGC2t2ewaT+NPYp46bNY4tA3xxvnXy69mSBggWKO8+mV1IUQqd3/JfweujvkBx8GvLxNNygoQyrvGwy3g3NxR/DOddjve6QGTZfRyywSxPd0VsU5RUIvNxwR6iiQfrCSaMOVrxCUDaCKuazIYSEvOzYW0S42eF/WFjqBHeIzlvuDNLOpMIY+I+CaADBpqXzT+pO2SIfv62uodtifYNUp4jk3pIMKvFnWYbc6jhUg0KjbgcqrFHF34ygwm1WX1tRT5bjQobFNdxKTWc2MENcImx6z+SkS5FazIIraCJ6RfhILqpftTNVtoYPo3GjbQ5HPV2KMR4gzyU7OfLOW0lfaZPWp2O2SlrPokSYfAtKprNpMdmxDUq15OU/0RkiYsnef5OJuNYZiPRxRESMgRjoyzrscqojUrMVblRVMYN7Ez4QGLnK2N23fs5W44nMPy+PrynsX/VQiUgDlCy3EAYA7k+zmH2VYjqEMWjAb+0WIy+0JChONivyupT4oVl/8cy5L5cH71XkfklOHeyLiJzSIae5aDzB7Bll4Y/mLfD9CF0=
  - fD4FlwguETeU+0x6dIcial+bS0ncXX8hSGNseP0pHxEd4tweLN1p/c+T4P1fU+XZaKunOHKVQM7YDL40NvLLuD6Eyy1kZSXY0Z9QJXQQRXKzEAu7DN14+m5DHOqmudmLpiLTCzi2i3UMcc1NEvMC4qOVGq8RrVhQ5dkqdcgfX5n/ZkKnlQ31N1UtLzHBJQpEyUI+Y+ZYu+mm6lbHOOB3J05DrYiiYyYw1EOg64Q3pI8RUE7YEooEzbLMr2mtT/Y3E9cC26XJ8fte6F+APl9fJqJimkBVZS5M512UrMcWgKU+b/2hIe/RvlB3RFlfUFOutwCVm4zw8e3Hr/OulAnXsyAfGx/MmKUr2yishIyVC0zA6cPUUC9re6omdF6gfKGUpSg0W8D+sJnz22JlaPlQnBl8wu1U5FydkSETrq4OwnmsPbdt4QCvgGX9VdwuAWAIRMTNKRcpYMQqsH/TXbjw5N+hHU2VX+o2Nj5OpBtMnlLEO7JYMGCB2v3RpBbgZmsu0XUhP11pkUnNnGRc0Tu8ABAIKQs4ASMOSLlLaIW0Hki59mRlwvSLfltyb6WsEcZBQgbvXB8/BiJDZHwhjaC7SBtxd9VQDoql7i2labo+sLO2woH1FPDLrsiAFdg8uJuElqVYA3lYkAccmyCnsv4aUbv//4ay3bC7+yPelEs/niM=
sudo: false
after_success: find _site -type f -exec curl -u $FTP_USER:$FTP_PASSWORD --ftp-create-dirs
  -T {} ftp://ftp.manchestercurious.com/manchestercurious.com/public_html/showcase/{}
  \;
