language: ruby
rvm:
- 2.2.3
before_script:
- chmod +x ./script/cibuild
script: "./script/cibuild"
branches:
  only:
  - master
  - gh-pages
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
sudo: false
dd:
  secure: Uf5IBWf6wKH14h4nPnvhKw3Drg7CQ4eLextQaK5fJj+SwhTc9CGESsTEZx05QYGvxgwlXVeba0aclU7Pe+lZV/Nj10OwAcONYbRneKp8xCp2fxlcgGnX/T8KwioOwK+PjHMiDaSvFAxzUIcizELwSIdafEg00vT0s/vLqvwcYJurGD5lwsREsM6jHFgdVgeVdvdvmelPSKharouUFxXlgDPZIyV3YJYa/Rk19ATmzbRcYPkHrPj3XgeEv8s+cZ/RiMnf12nQFS/0FJiIJGpO/lKzKylTY4U5XySU/4nrFBD1oGmQFNjJ1FdvcPp7627O/VZImG6criW8STw2ptOgWhumb6/iS8O7meF4WOUN1X4GUSJL8AT7TWkHJNj/uTY+XNN9bxTtDGCo6IgFffAFVt5MmuEXhFbnwbS+m7/xsD190iVTI79EYltIqxGyBKgvZ10nHNvlTvJploGuzZ3yO5kKO4WWB/vu85VzE0o5McuSRYyNtX9kvlcomjDpq5r98BuNjQRQNQyQutJhV09xi/dE4Vofs8aTVJd2KeiO1rQ3UmEsXKProG02WLWvYed8eMLlH8aMlSvVuQVRBDSz5vljVzVwcLTwt1JCuZs6IwSQ5jqqWb55SyYBiC35F9gmijgrMf5XXI+9rh6VMx8ttSu9q2/WxbdWS0vLq+s7668=
after_success:
  "curl --ftp-create-dirs -T _site -u $FTP_USER:$FTP_PASSWORD ftp://ftp.manchestercurious.com/manchestercurious.com/public_html/showcase"