title: Manchester Curious
description: Manchester Curious aims to open the doors of some of Manchester’s finest buildings and hidden spaces to discover the secrets and innovations behind them.
name: Manchester Curious
author: MCRCurious2016
url: http://manchester-curious.github.io/staging/
highlighter: rouge
twitter:
  username: MCRCurious2016
facebook:
  app_id: 1464193933910020
logo: /images/logo@2x.gif
exclude: ["vendor", "README.md", "package.json", "gulpfile.js", "bower.json", "CHANGELOG.md", "Gemfile", "script", "scss", "Rakefile", "bower_components", "node_modules"]
mapbox_api_key: pk.eyJ1IjoibWFuY2hlc3RlcmN1cmlvdXNtYXAiLCJhIjoiY2lubTZsY2V1MDBiNXcya2wwc3FyNjJsaiJ9.Ra0-KaX_IvxzcTfRMoyBGQ
sass:
    sass_dir: scss

social:
  links:
    - https://twitter.com/mcrcurious2016
    - https://www.facebook.com/manchestercurious
    - https://www.instagram.com/mcrcurious/
gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-sass-converter